FROM registry.cn-hangzhou.aliyuncs.com/wybioinfo/tidyverse:4.4
# RUN apt-get update -y
# RUN apt-get install libbz2-dev -y

# docker build -t registry.cn-hangzhou.aliyuncs.com/wybioinfo/tidyverse:4.4 .


