FROM registry.cn-hangzhou.aliyuncs.com/wybioinfo/tidyverse:4.4
RUN apt-get update -y
RUN  apt install cmake -y
# docker build -t registry.cn-hangzhou.aliyuncs.com/wybioinfo/mendelian-randomization-rstudio .


